### ISSUE TITLE
Add discussion on combined KAT/PAT

### ISSUE THREAD

**Issue by ionut-arm** [yaronf/draft-tls-attestation#3]
One of the potential usage patterns of the extension is through a combined key and platform attestation token. Currently the draft discusses only the possibility of having the KAT and PAT as separate tokens. We should either include details about a single token doing both roles, or make the current description more generic (though I'd lean towards the former).

**Comment by hannestschofenig** [comment]
This issue is not applicable to the TLS attestation draft. We might add a line or two in the KAT draft about the possibility of other design approaches.
